import { Manrope } from '@next/font/google';
import './globals.css';

import Header from '@/components/header/header';

import Head from 'next/head';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <body className={`${manrope.className}`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
