import { Manrope } from '@next/font/google';
import './globals.css';
import 'swiper/css';
import Header from '@/components/header/header';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className}`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
